### ISSUE TITLE
Pliki CAD do osłony radiacyjnej

### ISSUE THREAD

**Issue by SP8EBC** [SQ9MDD/StacjaPogody#1]
Cześć,
Czy możesz gdzieś zapodać te pliki z których drukujesz osłone radiacyjną?

**Comment by SQ9MDD** [comment]
Cześć tutaj masz u mnie:

https://github.com/SQ9MDD/StacjaPogody/tree/main/stl

Oryginał jest na thingiverse:

https://www.thingiverse.com/thing:1067700
